version: "3"

tasks:
  backend:build:
    cmds:
      - docker build -t globe-pin-backend ./backend

  backend:run:
    cmds:
      - docker run --env-file ./backend/.env -p 3001:3001 globe-pin-backend

  backend:
    cmds:
      - task: backend:build
      - task: backend:run

  frontend:dev:
    cmds:
      - npm run dev

  frontend:prod:build:
    cmds:
      - docker build -t globe-pin-frontend .

  frontend:prod:run:
    cmds:
      - docker run --name globe-pin-frontend -p 8080:80 globe-pin-frontend

  frontend:prod:
    cmds:
      - task: frontend:prod:build
      - task: frontend:prod:run
